# Obtaining the Dataset: Karate Club

PyTorch Geometric is an extension library to the popular deep learning framework PyTorch, and consists of various methods and utilities to ease the implementation of Graph Neural Networks.

At first, we need a dataset for training, validating and testing the Graph Neural Network (GNN). In this hands-on practice, I will use the well-known Zachary's karate club dataset. This graph describes a social network of **34 members** of a karate club and documents links between members who interacted outside the club. The task is to detect communities that arise from the member's interaction.

**Dataset details:**
**

PyTorch Geometric provides an easy access to this dataset via the **torch_geometric.datasets** subpackage.

In [134]:
from torch_geometric.datasets import KarateClub


dataset = KarateClub()#stores the entire dataset - with all the graphs
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs in the dataset: {len(dataset)}')
print(f'Number of classes: {dataset.num_classes}')

Dataset: KarateClub():
Number of graphs in the dataset: 1
Number of classes: 4


PyTorch Geometric provides a **Data** class. An object of the **Data** class is a homogeneous graph. Such an object can hold node-level, link-level and graph-level attributes. 

In general, **Data** tries to mimic the behavior of a regular Python dictionary. 

Some of the commonly useful properties of this class and its objects are:
1. **num_node_features**: int
2. **num_nodes**: int
3. **num_edge_features**: int
4. **num_edges**: int
5. **num_classes**: int
6. num_edge_types: int
7. num_node_types: int

Some of the useful methods of this class and its objects are:
1. .is_undirected()
2. .has_self_loops()

In [136]:
for (i,graph) in zip(range(len(dataset)),dataset):
        print(f'{i}-th graph: {graph}')
        print(f'------------')
        print(f'Number of nodes: {graph.num_nodes}')
        print(f'Number of node features: {graph.num_node_features}')
        print(f'Number of edges: {graph.num_edges}')
        print(f'Number of edge features: {graph.num_edge_features}')
        print(f'Average node degree: {graph.num_edges / graph.num_nodes:.2f}')
        print(f'Number of training nodes: {graph.train_mask.sum()}')
        print(f'Has isolated nodes(nodes without edges): {graph.has_isolated_nodes()}')
        print(f'Has self-loops: {graph.has_self_loops()}')
        print(f'Is undirected: {graph.is_undirected()}')

0-th graph: Data(x=[34, 34], edge_index=[2, 156], y=[34], train_mask=[34])
------------
Number of nodes: 34
Number of node features: 34
Number of edges: 156
Number of edge features: 0
Average node degree: 4.59
Number of training nodes: 4
Has isolated nodes(nodes without edges): False
Has self-loops: False
Is undirected: True


So, only 4 nodes are labeled. Labels of rest of the nodes are to be inferred.

In [49]:
dataset[0].y #ground-truth label of all the nodes in the graph

tensor([1, 1, 1, 1, 3, 3, 3, 1, 0, 1, 3, 1, 1, 1, 0, 0, 3, 1, 0, 1, 0, 1, 0, 0,
        2, 2, 0, 0, 2, 0, 0, 2, 0, 0])

In [56]:
len(dataset[0].y) #number of labels = number of nodes in the graph

34

In [66]:
import numpy as np
len(np.unique(np.array(dataset[0].y)))#np.unique() is a utility from the numpy library that removes duplicates in a numpy array

4

In [54]:
dataset[0].x #feature vector of all the nodes in this graph

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [55]:
len(dataset[0].x) #number of nodes

34

In [120]:
dataset[0].x[33] #feature vector of 34th node

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [121]:
len(dataset[0].x[33])

34

By printing '**edge_index**', we can understand how PyG represents graph connectivity internally. We can see that for each edge, edge_index holds a tuple of two node indices, where the first value describes the node index of the source node and the second value describes the node index of the destination node of an edge.

This representation is known as the **COO format** (co-ordinate format) commonly used for representing sparse matrices. Instead of holding the adjacency information in a dense representation, PyG represents graphs sparsely, which refers to only holding the coordinates/values for which entries are non-zero.

In [50]:
dataset[0].edge_index #node-connectivity representation

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,
          3,  3,  3,  3,  3,  4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,
          7,  7,  8,  8,  8,  8,  8,  9,  9, 10, 10, 10, 11, 12, 12, 13, 13, 13,
         13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 20, 20, 21,
         21, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 27, 27,
         27, 27, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 31, 31, 31, 31, 31,
         31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
         33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33],
        [ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 17, 19, 21, 31,  0,  2,
          3,  7, 13, 17, 19, 21, 30,  0,  1,  3,  7,  8,  9, 13, 27, 28, 32,  0,
          1,  2,  7, 12, 13,  0,  6, 10,  0,  6, 10, 16,  0,  4,  5, 16,  0,  1,
          2,  3,  0,  2, 30, 32, 33,  2, 33,  0,  4

In [57]:
len(dataset[0].edge_index)

2

In [79]:
import torch
torch.transpose(dataset[0].edge_index,0,1)

tensor([[ 0,  1],
        [ 0,  2],
        [ 0,  3],
        [ 0,  4],
        [ 0,  5],
        [ 0,  6],
        [ 0,  7],
        [ 0,  8],
        [ 0, 10],
        [ 0, 11],
        [ 0, 12],
        [ 0, 13],
        [ 0, 17],
        [ 0, 19],
        [ 0, 21],
        [ 0, 31],
        [ 1,  0],
        [ 1,  2],
        [ 1,  3],
        [ 1,  7],
        [ 1, 13],
        [ 1, 17],
        [ 1, 19],
        [ 1, 21],
        [ 1, 30],
        [ 2,  0],
        [ 2,  1],
        [ 2,  3],
        [ 2,  7],
        [ 2,  8],
        [ 2,  9],
        [ 2, 13],
        [ 2, 27],
        [ 2, 28],
        [ 2, 32],
        [ 3,  0],
        [ 3,  1],
        [ 3,  2],
        [ 3,  7],
        [ 3, 12],
        [ 3, 13],
        [ 4,  0],
        [ 4,  6],
        [ 4, 10],
        [ 5,  0],
        [ 5,  6],
        [ 5, 10],
        [ 5, 16],
        [ 6,  0],
        [ 6,  4],
        [ 6,  5],
        [ 6, 16],
        [ 7,  0],
        [ 7,  1],
        [ 7,  2],
        [ 

By printing '**edge_index**', we can understand how PyG represents graph connectivity internally. We can see that for each edge, edge_index holds a tuple of two node indices, where the first value describes the node index of the source node and the second value describes the node index of the destination node of an edge.

This representation is known as the **COO format** (co-ordinate format) commonly used for representing sparse matrices. Instead of holding the adjacency information in a dense representation, PyG represents graphs sparsely, which refers to only holding the coordinates/values for which entries are non-zero.

In [51]:
dataset[0].edge_attr #Edge feature matrix (default: None)

In [92]:
dataset[0].pos #Node position matrix (default: None)

## Implementing a Graph Neural Network (GNN)

Next, we implement a 3-layered GNN. Each layer performs the following graph convolution operation ([Kipf et al. (2017)](https://arxiv.org/abs/1609.02907)):

$$
\mathbf{x}_v^{(\ell + 1)} = \mathbf{W}^{(\ell + 1)} \sum_{w \in \mathcal{N}(v) \, \cup \, \{ v \}} \frac{1}{c_{w,v}} \cdot \mathbf{x}_w^{(\ell)}
$$

where, $\mathbf{W}^{(\ell + 1)}$ denotes a **trainable weight matrix** of shape `[num_output_features, num_input_features]` and $c_{w,v}$ refers to a fixed normalization coefficient for each edge.

PyG implements this layer via its [`GCNConv`](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GCNConv) class, specifically the `forward` function in it. It is executed by passing in the node-feature representation `x` and the COO graph-connectivity representation `edge_index`.

The Graph Neural Network (GNN) architecture is described in a child class `GCN` derived from the `torch.nn.Module` class of PyTorch. The `GCN` class initializes the architecture of the network in `__init__` and defines the computation flow of the network in `forward`. The network has three graph convolution layers, which corresponds to aggregating 3-hop neighborhood information around each node (all nodes up to 3 "hops" away). In addition, the GCNConv layers reduce the node feature dimensionality to  $2$ , *i.e.*,  $34 \rightarrow 4 \rightarrow 4 \rightarrow 2$. . Each GCNConv layer is enhanced by a **tanh** non-linearity. A **linear transformation** (`torch.nn.Linear`) acts as a classifier and maps the output of the $3^{rd}$ **tanh** to one of the 4 categories.

Finally, we create an object `model` of the `GCN` class.

<span style="color:red">     **DOUBTs:** WHY DO WE NEED THE `tanh`? WHAT IS IT'S FUNCTION?    </span>

In [101]:
#import torch
from torch_geometric.nn import GCNConv


class GCN(torch.nn.Module):
    def __init__(self):#define the layers of our GNN and initializes them
        super().__init__()
        torch.manual_seed(1234)#sets the seed for random number generation
        self.conv1 = GCNConv(dataset.num_features, 4)
        self.conv2 = GCNConv(4, 4)
        self.conv3 = GCNConv(4, 2)
        self.classifier = torch.nn.Linear(2, dataset.num_classes)

    def forward(self, data): #defines the computation flow of our GNN
        h = self.conv1(data.x, data.edge_index)
        h = h.tanh()
        h = self.conv2(h, data.edge_index)
        h = h.tanh()
        h = self.conv3(h, data.edge_index)
        h = h.tanh()  # Final GNN embedding space.
        
        # Apply a final (linear) classifier.
        out = self.classifier(h)

        return out, h #returns both the output of the final classifier as well as the final node embeddings produced by our GNN

model = GCN() 
print(model) #prints a summary of our model

GCN(
  (conv1): GCNConv(34, 4)
  (conv2): GCNConv(4, 4)
  (conv3): GCNConv(4, 2)
  (classifier): Linear(in_features=2, out_features=4, bias=True)
)


Here, `torch.nn.Linear` applies the following linear transformation to the input `x`: 

$$\mathbf{y} = \mathbf{x}\mathbf{A}^\mathbf{T} + \mathbf{b}$$

In [102]:
m=torch.nn.Linear(3,2)#computes (xA^T+b) where, x is the feature vector, b is the bias vector
m

Linear(in_features=3, out_features=2, bias=True)

In [103]:
m.weight#A

Parameter containing:
tensor([[ 0.0592,  0.0376,  0.0243],
        [-0.5017,  0.5573,  0.5512]], requires_grad=True)

In [104]:
m.bias#b

Parameter containing:
tensor([-0.3975,  0.1428], requires_grad=True)

In [105]:
x=torch.randn(1,3)
x

tensor([[-0.5541,  1.4976, -0.4817]])

In [106]:
m(x)#forward pass of the linear classifier

tensor([[-0.3856,  0.9899]], grad_fn=<AddmmBackward0>)

## Training the GNN

First, we define a loss critertion (here, [`CrossEntropyLoss`](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html)).

In [107]:
criterion = torch.nn.CrossEntropyLoss()

Then, we initialize a stochastic gradient optimizer (here, [`Adam`](https://pytorch.org/docs/stable/optim.html?highlight=adam#torch.optim.Adam))

In [108]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

After that, we perform multiple rounds of optimization, where each round consists of a forward and backward pass to compute the gradients of our model parameters w.r.t. to the loss derived from the forward pass.

In [111]:
for epoch in range(401):
    optimizer.zero_grad()  # Clear gradients.
    out, h = model(dataset[0])  # Perform a single forward pass.
    loss = criterion(out[dataset[0].train_mask], dataset[0].y[dataset[0].train_mask])  # Compute the loss solely based on the training nodes.
    loss.backward()  # Derive gradients.
    optimizer.step()

**Final node embeddings produced by the trained GNN:**

In [124]:
new_embeddings_per_node = model(dataset[0])[1]
new_embeddings_per_node

tensor([[-0.9959, -0.9922],
        [-1.0000, -0.4081],
        [-0.9997,  0.9750],
        [-0.9993, -0.5114],
        [ 0.9920, -0.9936],
        [ 0.9982, -0.9984],
        [ 0.9982, -0.9984],
        [-0.9955, -0.0980],
        [-0.9919,  0.9885],
        [-0.9734,  0.9906],
        [ 0.9921, -0.9936],
        [-0.8716, -0.7853],
        [-0.9762, -0.7062],
        [-0.9956,  0.5316],
        [-0.9540,  0.9966],
        [-0.9531,  0.9966],
        [ 0.9990, -0.9962],
        [-0.9771, -0.6140],
        [-0.9515,  0.9969],
        [-0.9804,  0.4159],
        [-0.9462,  0.9966],
        [-0.9808, -0.5847],
        [-0.9519,  0.9966],
        [-0.0488,  0.9993],
        [ 0.9959,  0.9929],
        [ 0.9927,  0.9942],
        [-0.9637,  0.9987],
        [ 0.4140,  0.9964],
        [-0.7756,  0.9934],
        [-0.9688,  0.9996],
        [-0.9927,  0.9875],
        [ 0.6807,  0.9952],
        [-0.9999,  1.0000],
        [-1.0000,  1.0000]], grad_fn=<TanhBackward0>)

**Probability of a node to belong to each label:**

In [125]:
new_label_per_node = model(dataset[0])[0]
new_label_per_node

tensor([[-0.1725,  5.4453, -5.5782,  0.1491],
        [ 1.4741,  3.7828, -3.9650, -1.4976],
        [ 5.3494, -0.1770, -0.1143, -5.3670],
        [ 1.1832,  4.0769, -4.2505, -1.2067],
        [-4.8904,  0.8330,  0.5678,  6.1149],
        [-4.9185,  0.8322,  0.5738,  6.1468],
        [-4.9185,  0.8322,  0.5738,  6.1468],
        [ 2.3326,  2.8850, -3.0883, -2.3520],
        [ 5.3686, -0.2334, -0.0530, -5.3813],
        [ 5.3309, -0.2825,  0.0101, -5.3320],
        [-4.8906,  0.8328,  0.5681,  6.1151],
        [ 0.1127,  4.5642, -4.6176, -0.0572],
        [ 0.5824,  4.5808, -4.7212, -0.5922],
        [ 4.0971,  1.0829, -1.3361, -4.1140],
        [ 5.3014, -0.3446,  0.0868, -5.2903],
        [ 5.2993, -0.3468,  0.0897, -5.2876],
        [-4.9145,  0.8240,  0.5824,  6.1434],
        [ 0.8429,  4.3189, -4.4672, -0.8528],
        [ 5.2966, -0.3513,  0.0954, -5.2839],
        [ 3.7369,  1.3787, -1.6110, -3.7447],
        [ 5.2830, -0.3630,  0.1112, -5.2670],
        [ 0.9339,  4.2436, -4.3971

A node is predicted to have a label that has the highest probability.

Since only 4 nodes are labeled in the entire dataset, we present below their labels as predicted by the trained GNN and as mentioned in the dataset. This would help us to get an understanding of the training accuracy achieved by the GNN. Due to lack of any more labeled nodes, we don't have test set for measuring test accuracy.

In [133]:
new_label_per_node[dataset[0].train_mask].argmax(dim=1)

tensor([1, 3, 0, 2])

In [132]:
dataset[0].y[dataset[0].train_mask]

tensor([1, 3, 0, 2])

TO DO:
----------
1. Print the evolution of weight matrix during the training of GNN. Print all parameters of importance during training of GNN.
2. Implement the optional exercise of Cora exercise.
3. Implement an MLP and check its performance in this case.